### ISSUE TITLE
'Add Tab' dialog obscured

### ISSUE THREAD

**Issue by humantex** [pawedWolf/fox-admintheme#3]
When editing a page/article and attempting to add a new tab - the add-part-dialog div pops up, but it's behind the 'mask' div, which is apparently some type of demo within the theme. Unfortunately there's no way to dismiss the mask and get back into editing mode. The lower-left demo div with the close button is also behind the mask (with its 9999 z-index), and nothing is clickable anywhere within the edit pane.

I've just started testing Wolf, so I'm not sure of every function that should actually be available in the admin end, but this leaves no choice but to back-page and loose any editing that was already begun.

**Comment by ivapelc** [comment]
The same problem is with any box/popup window. The easiest way to overcome it is to disable the #mask div with adding !important to display:none; in its styles in part.elements.css...

**Comment by SamBrishes** [comment]
I'm sorry, but 2016 was a shitty year, where I had no internet.

But back to topic. I already posted a small HotFix on the [official Wolf CMS forum](https://www.wolfcms.org/forum/post20646.html#p20646), which solves the problem with the overlay boxes and the mask:

## HotFix 1

**✗ Error**
The overlay boxes are behind the mask and thus they cannot be operated via the cursor.

**✓ Solution**
- Remove the line `z-index: 20;` within the `fox/css/part.elements.css` file on line 404 (inside the `#main` specification).
- Change the value `bottom: 50px;` to `bottom: -25px;` within the same file on line 630 (inside the `#footer p.stats:after` specification)

Thanks to @ivapelc for the answer. ^^ (I will add this HotFix, after I set up the GitHub environment on my computer)

Sincerely,
Sam.
